const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Plugins.TextBox,
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Behaviors.Fade,
		C3.Plugins.TiledBg,
		C3.Plugins.progressbar,
		C3.Behaviors.Rotate,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.TextBox.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.Text.Acts.SetBoolInstanceVar,
		C3.Plugins.Text.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Text.Acts.SetLineHeight,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Acts.SetLayerEffectEnabled,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.Sprite.Acts.SetWidth
	];
};
self.C3_JsPropNameTable = [
	{Ante_Porque: 0},
	{Antecedentes_Texto: 0},
	{Titulo_Antecedentes: 0},
	{Detalle_DNI: 0},
	{Info: 0},
	{Titulo_de_Asesinato: 0},
	{Preegunta: 0},
	{Explicacion_aPreguntas: 0},
	{Titulo_Max5: 0},
	{EntradaDeTexto: 0},
	{Texto_Loading: 0},
	{Mesa: 0},
	{Pedir_Documento: 0},
	{Pedir_Objeto: 0},
	{Pedir_Papeles: 0},
	{Silla: 0},
	{negro: 0},
	{Carlos: 0},
	{Mensajes: 0},
	{Guillermo_Telefono: 0},
	{mensajes: 0},
	{Guillermo: 0},
	{Betty_Telefono: 0},
	{Betty: 0},
	{Maria: 0},
	{Hugo: 0},
	{Samuel: 0},
	{Pablo: 0},
	{Andrea: 0},
	{Ashley: 0},
	{Joce: 0},
	{David: 0},
	{Stella: 0},
	{Mouse: 0},
	{Audio: 0},
	{Teclado: 0},
	{Anterior: 0},
	{Siguiente: 0},
	{Libro: 0},
	{Preguntar: 0},
	{Lapiz: 0},
	{Vandeja: 0},
	{Boton: 0},
	{Metralleta: 0},
	{Pistola: 0},
	{Combustible: 0},
	{Palanca: 0},
	{Veneno: 0},
	{Cuchillo: 0},
	{Detalle_DNI_Logos: 0},
	{Detalle_DNI_Logos2: 0},
	{Detalle_DNI_Logos3: 0},
	{Detalle_DNI_Logos4: 0},
	{Relleno_DNI: 0},
	{Tarjeta: 0},
	{Documento_Carlos: 0},
	{Documento_Joce: 0},
	{Documento_Andrea: 0},
	{Documento_Pablo: 0},
	{Documento_Maria: 0},
	{Documento_Guillermo: 0},
	{Documento_Ashley: 0},
	{Documento_Hugo: 0},
	{Documento_David: 0},
	{Documento_Betty: 0},
	{Documento_Samuel: 0},
	{Documento_Stella: 0},
	{Hoja_Antecedentes: 0},
	{Si_No_Carcel: 0},
	{Si_No_CausaAbierta: 0},
	{Si_No_Demanda: 0},
	{Si_No_Disturbios: 0},
	{Si_No_InfraccionLey: 0},
	{Si_No_Juicio: 0},
	{Dialogos: 0},
	{Sigues_NoSigues: 0},
	{Celular: 0},
	{fondo_Chat: 0},
	{Trabajo_Boton: 0},
	{QueHacia_Boton: 0},
	{Borde_Der: 0},
	{Borde_Izq: 0},
	{Relacion_Boton: 0},
	{Dever_Boton: 0},
	{Vieron_Boton: 0},
	{fondo_Chat_Respuesta: 0},
	{Volver: 0},
	{Hoja_Para_Escrivir: 0},
	{Libreta_INFO_Asesinato: 0},
	{GameOver: 0},
	{Luces_Final: 0},
	{Contorno_EstasSeguro: 0},
	{Estas_Seguro: 0},
	{No: 0},
	{Texto_Cartel: 0},
	{Tilde: 0},
	{Documento_Conf: 0},
	{Explicacion_Menu: 0},
	{Lapiz_Conf: 0},
	{Libro_Conf: 0},
	{Objeto_Conf: 0},
	{Objeto_Conf2: 0},
	{Pregunta_Conf: 0},
	{Divicion_de_textos: 0},
	{Pregunta_Conf2: 0},
	{Contorno_Play_Etc: 0},
	{Fondo_Menu: 0},
	{L_Der: 0},
	{Play: 0},
	{Controles: 0},
	{Niveles: 0},
	{Configuracion_Fondo: 0},
	{Fondo_Negro: 0},
	{M_On_Off: 0},
	{Prendido_No: 0},
	{Musica: 0},
	{Musica_Texto: 0},
	{Lluvia: 0},
	{Fondo_Menu_Negro: 0},
	{Ojos2: 0},
	{Signo_de_Pregunta: 0},
	{Ojos3: 0},
	{Desvanecer: 0},
	{Transicion: 0},
	{Titulo_del_Juego: 0},
	{Opa_Num: 0},
	{Ver_Fal: 0},
	{Titulo_Ecena: 0},
	{FlechaDer: 0},
	{Nombre_Asesinado: 0},
	{Numeros_Casos: 0},
	{Casa: 0},
	{FondoEnMosaico2: 0},
	{Persona_Muerta: 0},
	{Persona_Muerta2: 0},
	{Persona_Muerta3: 0},
	{BarraDeProgreso: 0},
	{Humo: 0},
	{Girar: 0},
	{loading: 0},
	{luces_Policia: 0},
	{subrallo: 0},
	{longitud: 0},
	{Barra_De_Carga: 0},
	{Personajes: 0},
	{Preguntas: 0},
	{Siguiente_Anterior: 0},
	{GameOver_Opa: 0},
	{GameOver_Tam: 0},
	{Casos: 0},
	{Numero_de_Casos: 0},
	{Cual_Musica: 0},
	{Hab_Des_Mause: 0}
];

self.InstanceType = {
	Ante_Porque: class extends self.ITextInstance {},
	Antecedentes_Texto: class extends self.ITextInstance {},
	Titulo_Antecedentes: class extends self.ITextInstance {},
	Detalle_DNI: class extends self.ITextInstance {},
	Info: class extends self.ITextInstance {},
	Titulo_de_Asesinato: class extends self.ITextInstance {},
	Preegunta: class extends self.ITextInstance {},
	Explicacion_aPreguntas: class extends self.ITextInstance {},
	Titulo_Max5: class extends self.ITextInstance {},
	EntradaDeTexto: class extends self.ITextInputInstance {},
	Texto_Loading: class extends self.ITextInstance {},
	Mesa: class extends self.ISpriteInstance {},
	Pedir_Documento: class extends self.ISpriteInstance {},
	Pedir_Objeto: class extends self.ISpriteInstance {},
	Pedir_Papeles: class extends self.ISpriteInstance {},
	Silla: class extends self.ISpriteInstance {},
	negro: class extends self.ISpriteInstance {},
	Carlos: class extends self.ISpriteInstance {},
	Guillermo: class extends self.ISpriteInstance {},
	Betty: class extends self.ISpriteInstance {},
	Maria: class extends self.ISpriteInstance {},
	Hugo: class extends self.ISpriteInstance {},
	Samuel: class extends self.ISpriteInstance {},
	Pablo: class extends self.ISpriteInstance {},
	Andrea: class extends self.ISpriteInstance {},
	Ashley: class extends self.ISpriteInstance {},
	Joce: class extends self.ISpriteInstance {},
	David: class extends self.ISpriteInstance {},
	Stella: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Teclado: class extends self.IInstance {},
	Anterior: class extends self.ISpriteInstance {},
	Siguiente: class extends self.ISpriteInstance {},
	Libro: class extends self.ISpriteInstance {},
	Preguntar: class extends self.ISpriteInstance {},
	Lapiz: class extends self.ISpriteInstance {},
	Vandeja: class extends self.ISpriteInstance {},
	Boton: class extends self.ISpriteInstance {},
	Metralleta: class extends self.ISpriteInstance {},
	Pistola: class extends self.ISpriteInstance {},
	Combustible: class extends self.ISpriteInstance {},
	Palanca: class extends self.ISpriteInstance {},
	Veneno: class extends self.ISpriteInstance {},
	Cuchillo: class extends self.ISpriteInstance {},
	Detalle_DNI_Logos: class extends self.ISpriteInstance {},
	Detalle_DNI_Logos2: class extends self.ISpriteInstance {},
	Detalle_DNI_Logos3: class extends self.ISpriteInstance {},
	Detalle_DNI_Logos4: class extends self.ISpriteInstance {},
	Relleno_DNI: class extends self.ITextInstance {},
	Tarjeta: class extends self.ISpriteInstance {},
	Documento_Carlos: class extends self.ISpriteInstance {},
	Documento_Joce: class extends self.ISpriteInstance {},
	Documento_Andrea: class extends self.ISpriteInstance {},
	Documento_Pablo: class extends self.ISpriteInstance {},
	Documento_Maria: class extends self.ISpriteInstance {},
	Documento_Guillermo: class extends self.ISpriteInstance {},
	Documento_Ashley: class extends self.ISpriteInstance {},
	Documento_Hugo: class extends self.ISpriteInstance {},
	Documento_David: class extends self.ISpriteInstance {},
	Documento_Betty: class extends self.ISpriteInstance {},
	Documento_Samuel: class extends self.ISpriteInstance {},
	Documento_Stella: class extends self.ISpriteInstance {},
	Hoja_Antecedentes: class extends self.ISpriteInstance {},
	Si_No_Carcel: class extends self.ISpriteInstance {},
	Si_No_CausaAbierta: class extends self.ISpriteInstance {},
	Si_No_Demanda: class extends self.ISpriteInstance {},
	Si_No_Disturbios: class extends self.ISpriteInstance {},
	Si_No_InfraccionLey: class extends self.ISpriteInstance {},
	Si_No_Juicio: class extends self.ISpriteInstance {},
	Celular: class extends self.ISpriteInstance {},
	fondo_Chat: class extends self.ISpriteInstance {},
	Trabajo_Boton: class extends self.ISpriteInstance {},
	QueHacia_Boton: class extends self.ISpriteInstance {},
	Borde_Der: class extends self.ISpriteInstance {},
	Borde_Izq: class extends self.ISpriteInstance {},
	Relacion_Boton: class extends self.ISpriteInstance {},
	Dever_Boton: class extends self.ISpriteInstance {},
	Vieron_Boton: class extends self.ISpriteInstance {},
	fondo_Chat_Respuesta: class extends self.ISpriteInstance {},
	Volver: class extends self.ISpriteInstance {},
	Hoja_Para_Escrivir: class extends self.ISpriteInstance {},
	Libreta_INFO_Asesinato: class extends self.ISpriteInstance {},
	GameOver: class extends self.ITextInstance {},
	Luces_Final: class extends self.ISpriteInstance {},
	Contorno_EstasSeguro: class extends self.ISpriteInstance {},
	Estas_Seguro: class extends self.ITextInstance {},
	No: class extends self.ISpriteInstance {},
	Texto_Cartel: class extends self.ITextInstance {},
	Tilde: class extends self.ISpriteInstance {},
	Documento_Conf: class extends self.ISpriteInstance {},
	Explicacion_Menu: class extends self.ITextInstance {},
	Lapiz_Conf: class extends self.ISpriteInstance {},
	Libro_Conf: class extends self.ISpriteInstance {},
	Objeto_Conf: class extends self.ISpriteInstance {},
	Objeto_Conf2: class extends self.ISpriteInstance {},
	Pregunta_Conf: class extends self.ISpriteInstance {},
	Divicion_de_textos: class extends self.ISpriteInstance {},
	Pregunta_Conf2: class extends self.ISpriteInstance {},
	Contorno_Play_Etc: class extends self.ISpriteInstance {},
	Fondo_Menu: class extends self.ISpriteInstance {},
	L_Der: class extends self.ISpriteInstance {},
	Play: class extends self.ITextInstance {},
	Controles: class extends self.ITextInstance {},
	Niveles: class extends self.ITextInstance {},
	Configuracion_Fondo: class extends self.ISpriteInstance {},
	Fondo_Negro: class extends self.ISpriteInstance {},
	M_On_Off: class extends self.ITextInstance {},
	Musica: class extends self.ISpriteInstance {},
	Musica_Texto: class extends self.ITextInstance {},
	Lluvia: class extends self.ISpriteInstance {},
	Fondo_Menu_Negro: class extends self.ISpriteInstance {},
	Ojos2: class extends self.ISpriteInstance {},
	Signo_de_Pregunta: class extends self.ISpriteInstance {},
	Ojos3: class extends self.ISpriteInstance {},
	Transicion: class extends self.ISpriteInstance {},
	Titulo_del_Juego: class extends self.ITextInstance {},
	Titulo_Ecena: class extends self.ITextInstance {},
	FlechaDer: class extends self.ISpriteInstance {},
	Nombre_Asesinado: class extends self.ITextInstance {},
	Numeros_Casos: class extends self.ITextInstance {},
	Casa: class extends self.ISpriteInstance {},
	FondoEnMosaico2: class extends self.ITiledBackgroundInstance {},
	Persona_Muerta: class extends self.ISpriteInstance {},
	Persona_Muerta2: class extends self.ISpriteInstance {},
	Persona_Muerta3: class extends self.ISpriteInstance {},
	BarraDeProgreso: class extends self.IProgressBarInstance {},
	Humo: class extends self.ISpriteInstance {},
	loading: class extends self.ISpriteInstance {},
	luces_Policia: class extends self.ISpriteInstance {},
	subrallo: class extends self.ISpriteInstance {},
	Barra_De_Carga: class extends self.ISpriteInstance {}
}